### ISSUE TITLE
Can SparseTIR support operations other than multiplication and addition?

### ISSUE THREAD

**Issue by gxiaotian** [uwsampl/sparsetir#101]
Hello,

I am new to SparseTIR and wonder whether it can support operations other than multiplication and addition.

For example, the below expression is valid SparseTIR or not?
<pre>
with T.sp_iter([I, J], "SR") as [i, j]:
       with T.init():
              Y[i, j] = 0.0
        Y[i] = Y[i, j] + (X[i] - X[j]) ** 2
</pre>

Thanks!

**Comment by yzh119** [comment]
Sorry for the very late reply, I just noticed this issue.

Yes of course, but I'm not sure if the parser can parse `**` correctly. A safer way would be
`T.power(X[i] - X[j], 2)`
